### ISSUE TITLE
encodeHex output length seems a tad lengthy

### ISSUE THREAD

**Issue by nathanhornby** [ivanakimov/hashids.node.js#18]
Hi, using `encodeHex()` to encode a mongodb ObjectId seems to produce a rather long string:

`var Hashids = require('hashids'), hashids = new Hashids('saltypops',8);`

Gives me:
`55a583ae9f1a205d700d4051` -> `OOrYGqvPRAFn1emPNz1a`

So is hashids unable to shorten the Id any further? I'm assuming this is a limitation? It doesn't mention in the docs so thought I'd check.

**Comment by nathanhornby** [comment]
Ah, have done a little more reading and I see this is a base64 encode/decode and that's the length we have to work with. Damn maths!

**Comment by ivanakimov** [comment]
Hi Nathan,

Good eye, I also noticed this as I was developing this feature. At the beginning it seems since it's a much longer alphabet, the ids would get shorter, but Hashids has a few features which add to the output being longer, like:

- separators are 1 character each
- there's a lottery character added for more "randomness"
- a few characters are reserved from the alphabet for these purposes, so the alphabet is shorter
- plus when converting from hex to Hashids, you have to break up hex into many numbers, so each number doesn't overflow in its own language
- etc etc...

So in the end, it really adds up and for MongoDB ids not a tremendous improvement. Damn maths, indeed!
